### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by HapeBroes** [jtl-software/connector-plugin-rpcview#1]
Hello,

this does not work with the current JTLConnector anymore.

In the development branch is a version but that does not work even.

Did you plan to update it?

Best Regards

**Comment by paprykasz** [comment]
Hey @HapeBroes,

thank you for your feedback.

We just updated connector-plugin-rpcviewer repository and fixed js problem related to asset loading in old version. There are now two branches  [core2_3](https://github.com/jtl-software/connector-plugin-rpcviewer/tree/core2_3) for core version 2 and 3 and [master](https://github.com/jtl-software/connector-plugin-rpcviewer/tree/master) for core 4.
Old version (core2_3) folder in plugins directory needs to be named **rpcview** and new one (master) **RpcViewer**.

Let me know if you have any questions.

All the best,
Patryk

**Comment by HapeBroes** [comment]
Hey @paprykasz ,

great thanks for the fast response. I will try it in the next few days as soon as I am not so busy anymore.

Best Regards

**Comment by HapeBroes** [comment]
Hey @paprykasz ,

it is working fine. Thanks.

Best Regards.
